### ISSUE TITLE
A new project

### ISSUE THREAD

**Issue by KittyGiraudel** [4ae9b8/4ae9b8#1]
We are about to launch BrowserHacks. Depending on whether or not people like it, we may do further versions, adding new features and such. But eventually, some day, we will stop working on BH, only keeping it up to date.

I really enjoyed working on this. This is why I think (and Fabrice does it too, he just said it on 4ae9b8) we need to think about a new project. Maybe something we could all dive in (most code from BH came either from Tim or from me).

So what do you think guys ? Anything you would like to work on ? Any project you never had the courage to start because it was too scary to handle on your own ?

I know some of you guys do not have much free time, so there is no deadline. No limit or anything. Just tell what you would like to do. We'll see if we can do it later.

... POKE ALL THE MEMBERS!
@FWeinb @Mobilpadde @SaraSoueidan @TimPietrusky @thebabydino

**Comment by Mobilpadde** [comment]
Sure, I'd love to do some weird project with you guys... :D

2013/2/20 Hugo Giraudel notifications@github.com
